name: Publish to Registry

on:
  release:
      types: [published]
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Get repository name
        id: get_repo_name
        run: echo ::set-env name=REPOSITORY_NAME::$(echo $GITHUB_REPOSITORY)

      - name: Get release version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | awk -F '/' '{print $3}')

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.REPOSITORY_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
